{
  "scanId": "1203b5fb-ba13-44a9-9dae-06cf3b7b3969",
  "status": "failed",
  "message": "Pipeline execution failed: Static analysis failed: Command failed: spoon-audit scan \"/Users/user/Downloads/smart‑audit‑assistant/web-dashboard/uploads/SafeContract.sol\" --no-ai\n/Users/user/Downloads/smart‑audit‑assistant/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020\n  warnings.warn(\nTraceback (most recent call last):\n  File \"/Users/user/Downloads/smart‑audit‑assistant/.venv/bin/spoon-audit\", line 7, in <module>\n    sys.exit(main())\n  File \"/Users/user/Downloads/smart‑audit‑assistant/.venv/lib/python3.9/site-packages/click/core.py\", line 1161, in __call__\n    return self.main(*args, **kwargs)\n  File \"/Users/user/Downloads/smart‑audit‑assistant/.venv/lib/python3.9/site-packages/click/core.py\", line 1082, in main\n    rv = self.invoke(ctx)\n  File \"/Users/user/Downloads/smart‑audit‑assistant/.venv/lib/python3.9/site-packages/click/core.py\", line 1697, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/Users/user/Downloads/smart‑audit‑assistant/.venv/lib/python3.9/site-packages/click/core.py\", line 1443, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/Users/user/Downloads/smart‑audit‑assistant/.venv/lib/python3.9/site-packages/click/core.py\", line 788, in invoke\n    return __callback(*args, **kwargs)\n  File \"/Users/user/Downloads/smart‑audit‑assistant/.venv/lib/python3.9/site-packages/click/decorators.py\", line 33, in new_func\n    return f(get_current_context(), *args, **kwargs)\nTypeError: scan() got an unexpected keyword argument 'tools'\n",
  "timestamp": 1754462986774
}